version: '3.9'

services:
  main-app:
    container_name: main-app
    build:
      context: ..
      dockerfile: Dockerfile
    command: sh -c "poetry run python3 -m alembic upgrade head && 
      poetry run python3 -m gunicorn app.main:create_app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    volumes:
      - ..:/code/
    ports:
      - 127.0.0.1:8000:8000
    env_file:
      - ../.env-non-dev
    depends_on:
      - db
    networks:
      - backend


networks:
  backend:
    driver: bridge