version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - 127.0.0.1:5433:5432
    env_file:
      - ../.env-non-dev
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge
